source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.1'

inhibit_all_warnings!

use_frameworks!
install! 'cocoapods', integrate_targets: true

workspace 'PebbleKitSportsAPIDemo.xcworkspace'
project 'PebbleKitSportsAPIDemo.xcodeproj'

target 'PebbleKitSportsAPIDemo' do
  pod 'PebbleKit', '4.0.0'
end
